### ISSUE TITLE
Passenger gem version breaks with Heroku

### ISSUE THREAD

**Issue by benrmatthews** [professorNim/starter-app#1]
When I deployed to Heroku, I got a '502 Bad Gateway' error.
Upgrading the Passenger gem to version '4.0.57' fixed the issue for me.
More details on the bug here: https://github.com/phusion/passenger/issues/1314

**Comment by professorNim** [comment]
Updated gemfile, https://github.com/professorNim/starter-app/commit/a06de6974b26b7426cfc2832850733a75c22c678
